[options]

; Database connection
db_host = localhost
db_port = 5432
db_user = odoodb
db_password = odoo123
db_name = odoo19data

; Server port
http_port = 8070

; Admin password
admin_passwd = admin

; Disable demo data
;without_demo = True

; Logging
;logfile = /var/log/odoo/odoo19.log

; Addon paths (relative)
addons_path = custom, addons,odoo/addons

